import { db, IBusiness } from '../config/db.js';
import { hashPassword } from '../utils/password.js';
import { hashPin } from '../utils/pin.js';

export function seedDatabase() {
  // If businesses are already seeded, do not duplicate
  if (db.businesses.size > 0) return;

  const defaultBusinesses: IBusiness[] = [
    {
      id: 'biz_rustic_fork',
      name: 'The Rustic Fork Bistro',
      slug: 'rustic-fork',
      email: 'manager@rusticfork.com',
      passwordHash: hashPassword('password123'),
      staffPinHash: hashPin('1234'),
      tier: 'combined',
      timezone: 'Asia/Kolkata',
      googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      googlePlaceId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
      loyaltyTarget: 5,
      loyaltyReward: 'Free Signature Artisan Pizza & Handcrafted Dessert',
      category: 'Artisanal Italian & Craft Dining',
      logoEmoji: '🍕',
      address: '42 Heritage Boulevard, Downtown Square',
      accentColor: '#0e7c66',
      active: true,
      spinWheelConfiguration: [
        { id: 'sw_1', rewardLabel: '20% Off Main Course', emoji: '🍝', weight: 30 },
        { id: 'sw_2', rewardLabel: 'Free Craft Mocktail', emoji: '🍹', weight: 25 },
        { id: 'sw_3', rewardLabel: 'Crispy Bruschetta Platter', emoji: '🥖', weight: 20 },
        { id: 'sw_4', rewardLabel: '15% Off Total Dining Bill', emoji: '🎟️', weight: 15 },
        { id: 'sw_5', rewardLabel: 'Double Loyalty Stamp Today', emoji: '⭐', weight: 7 },
        { id: 'sw_6', rewardLabel: 'Free Gelato Trio', emoji: '🍨', weight: 3 },
        { id: 'sw_7', rewardLabel: 'Free burger', emoji: '🍔', weight: 3 },
      ],
    },
    {
      id: 'biz_brew_co',
      name: 'Brew & Co. Specialty Coffee',
      slug: 'brew-co',
      email: 'manager@brewco.com',
      passwordHash: hashPassword('password123'),
      staffPinHash: hashPin('2468'),
      tier: 'loyalty',
      timezone: 'Asia/Kolkata',
      googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      googlePlaceId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
      loyaltyTarget: 6,
      loyaltyReward: 'Complimentary Single-Origin Pour Over & Fresh Croissant',
      category: 'Specialty Roastery & Espresso Bar',
      logoEmoji: '☕',
      address: '18 Roaster Lane, Arts District',
      accentColor: '#0e7c66',
      active: true,
      spinWheelConfiguration: [
        { id: 'sw_b1', rewardLabel: 'Free Upgrade to Large', emoji: '☕', weight: 40 },
        { id: 'sw_b2', rewardLabel: 'Free Butter Croissant', emoji: '🥐', weight: 30 },
        { id: 'sw_b3', rewardLabel: '20% Off Bag of Beans', emoji: '📦', weight: 30 },
      ],
    },
    {
      id: 'biz_velvet_lounge',
      name: 'Velvet Lounge & Tapas',
      slug: 'velvet-lounge',
      email: 'manager@velvetlounge.com',
      passwordHash: hashPassword('password123'),
      staffPinHash: hashPin('7777'),
      tier: 'spin',
      timezone: 'Asia/Kolkata',
      googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      googlePlaceId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
      loyaltyTarget: 5,
      loyaltyReward: 'VIP Cocktail Platter',
      category: 'Cocktails & Evening Tapas',
      logoEmoji: '🍸',
      address: '77 High Street, Waterfront Promenade',
      accentColor: '#0e7c66',
      active: true,
      spinWheelConfiguration: [
        { id: 'sw_v1', rewardLabel: '1 Free Tapas Dish', emoji: '🍢', weight: 35 },
        { id: 'sw_v2', rewardLabel: 'Signature Welcome Cocktail', emoji: '🍸', weight: 25 },
        { id: 'sw_v3', rewardLabel: '20% Off Evening Check', emoji: '✨', weight: 25 },
        { id: 'sw_v4', rewardLabel: 'Free Churros with Dark Chocolate', emoji: '🍫', weight: 15 },
      ],
    },
    {
      id: 'biz_glow_salon',
      name: 'Glow Hair & Wellness Studio',
      slug: 'glow-salon',
      email: 'manager@glowsalon.com',
      passwordHash: hashPassword('password123'),
      staffPinHash: hashPin('9999'),
      tier: 'review',
      timezone: 'Asia/Kolkata',
      googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      googlePlaceId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
      loyaltyTarget: 4,
      loyaltyReward: 'Free Botanical Hair Spa Treatment',
      category: 'Luxury Salon & Wellness',
      logoEmoji: '✨',
      address: '104 Bloom Avenue, Suite 3B',
      accentColor: '#0e7c66',
      active: true,
      spinWheelConfiguration: [
        { id: 'sw_g1', rewardLabel: '15% Off Any Service', emoji: '💇‍♀️', weight: 50 },
        { id: 'sw_g2', rewardLabel: 'Free Conditioning Treatment', emoji: '💆‍♀️', weight: 50 },
      ],
    },
    {
      id: 'biz_urban_spice',
      name: 'Urban Spice Kitchen',
      slug: 'urban-spice',
      email: 'manager@urbanspice.com',
      passwordHash: hashPassword('password123'),
      staffPinHash: hashPin('4321'),
      tier: 'spin-review',
      timezone: 'Asia/Kolkata',
      googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      googlePlaceId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
      loyaltyTarget: 5,
      loyaltyReward: 'Free Dessert',
      category: 'Contemporary Indian Dining',
      logoEmoji: '🍛',
      address: '12 Spice Market Road',
      accentColor: '#0e7c66',
      active: true,
      spinWheelConfiguration: [
        { id: 'sw_u1', rewardLabel: 'Free Appetizer', emoji: '🥟', weight: 50 },
        { id: 'sw_u2', rewardLabel: '10% Off Bill', emoji: '🏷️', weight: 50 },
      ],
    },
    {
      id: 'biz_zen_tea',
      name: 'Zenith Tea House',
      slug: 'zen-tea',
      email: 'manager@zentea.com',
      passwordHash: hashPassword('password123'),
      staffPinHash: hashPin('8765'),
      tier: 'loyalty-review',
      timezone: 'Asia/Kolkata',
      googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      googlePlaceId: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
      loyaltyTarget: 4,
      loyaltyReward: 'Complimentary Matcha Latte & Mochi',
      category: 'Artisanal Teahouse',
      logoEmoji: '🍵',
      address: '99 Blossom Lane',
      accentColor: '#0e7c66',
      active: true,
      spinWheelConfiguration: [],
    },
  ];

  for (const b of defaultBusinesses) {
    db.businesses.set(b.id, b);
  }

  db.saveToDisk();
}
